backend:
  name: github
  repo: gamer2810/supreme-adventure
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

media_folder: "assets/img/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Media Subpath", name: "media_subpath", widget: "hidden", default: "assets/img/uploads/" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm:ssZ[Z]", format: "LLL", picker_utc: false }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "TOC", name: "toc", widget: "boolean", default: true }
      - { label: "Comments", name: "comments", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
